package leetcode

import org.junit.Test

import org.junit.Assert.*
import kotlin.random.Random

class NumberofIslandsIITest {

    @Test
    fun `test case 1`() {
        val positions = arrayOf(
            intArrayOf(0, 0),
            intArrayOf(0, 1),
            intArrayOf(1, 2),
            intArrayOf(2, 1),
        )
        val answer = NumberofIslandsII().numIslands2(3, 3, positions)
        val expected = listOf(1, 1, 2, 3)
        assertEquals(expected, answer)
    }

    @Test
    fun `test case 2`() {
        val positions = arrayOf(
            intArrayOf(0, 0),
            intArrayOf(0, 2),
            intArrayOf(0, 1),
            intArrayOf(2, 1),
        )
        val answer = NumberofIslandsII().numIslands2(3, 3, positions)
        val expected = listOf(1, 2, 1, 2)
        assertEquals(expected, answer)
    }

    @Test
    fun `test case 3`() {
        val positions = arrayOf(
            intArrayOf(0, 0),
            intArrayOf(0, 1),
            intArrayOf(1, 2),
            intArrayOf(1, 2),
        )
        val answer = NumberofIslandsII().numIslands2(3, 3, positions)
        val expected = listOf(1, 2, 1, 2)
        assertEquals(expected, answer)
    }

    @Test
    fun `test case 4`() {
        val positions = arrayOf(
            intArrayOf(19, 28),
            intArrayOf(14, 38),
            intArrayOf(15, 44),
            intArrayOf(17, 12),
            intArrayOf(6, 19),
            intArrayOf(11, 69),
            intArrayOf(2, 30),
            intArrayOf(7, 43),
            intArrayOf(19, 6),
            intArrayOf(7, 29),
            intArrayOf(10, 21),
            intArrayOf(17, 55),
            intArrayOf(20, 66),
            intArrayOf(12, 28),
            intArrayOf(11, 64),
            intArrayOf(12, 52),
            intArrayOf(18, 15),
            intArrayOf(2, 52),
            intArrayOf(10, 20),
            intArrayOf(0, 50),
            intArrayOf(16, 5),
            intArrayOf(17, 25),
            intArrayOf(12, 67),
            intArrayOf(6, 45),
            intArrayOf(13, 17),
            intArrayOf(5, 55),
            intArrayOf(10, 42),
            intArrayOf(20, 17),
            intArrayOf(3, 26),
            intArrayOf(20, 61),
            intArrayOf(14, 10),
            intArrayOf(9, 1),
            intArrayOf(9, 69),
            intArrayOf(6, 29),
            intArrayOf(11, 53),
            intArrayOf(3, 66),
            intArrayOf(4, 45),
            intArrayOf(12, 65),
            intArrayOf(11, 35),
            intArrayOf(5, 67),
            intArrayOf(18, 35),
            intArrayOf(2, 57),
            intArrayOf(12, 12),
            intArrayOf(13, 53),
            intArrayOf(9, 65),
            intArrayOf(13, 0),
            intArrayOf(3, 18),
            intArrayOf(13, 39),
            intArrayOf(5, 54),
            intArrayOf(20, 43),
            intArrayOf(19, 29),
            intArrayOf(17, 37),
            intArrayOf(17, 45),
            intArrayOf(3, 38),
            intArrayOf(2, 61),
            intArrayOf(2, 65),
            intArrayOf(3, 21),
            intArrayOf(5, 40),
            intArrayOf(10, 4),
            intArrayOf(12, 36),
            intArrayOf(2, 8),
            intArrayOf(3, 33),
            intArrayOf(15, 4),
            intArrayOf(13, 35),
            intArrayOf(0, 45),
            intArrayOf(20, 29),
            intArrayOf(10, 66),
            intArrayOf(19, 7),
            intArrayOf(0, 46),
            intArrayOf(19, 11),
            intArrayOf(10, 22),
            intArrayOf(19, 0),
            intArrayOf(0, 9),
            intArrayOf(2, 20),
            intArrayOf(16, 64),
            intArrayOf(10, 37),
            intArrayOf(16, 49),
            intArrayOf(4, 20),
            intArrayOf(20, 68),
            intArrayOf(10, 38),
            intArrayOf(17, 59),
            intArrayOf(15, 54),
            intArrayOf(17, 60),
            intArrayOf(19, 18),
            intArrayOf(0, 60),
            intArrayOf(9, 62),
            intArrayOf(3, 69),
            intArrayOf(10, 44),
            intArrayOf(15, 2),
            intArrayOf(14, 44),
            intArrayOf(17, 0),
            intArrayOf(18, 42),
            intArrayOf(17, 28),
            intArrayOf(11, 10),
            intArrayOf(11, 42),
            intArrayOf(11, 67),
            intArrayOf(0, 32),
            intArrayOf(8, 0),
            intArrayOf(17, 6),
            intArrayOf(7, 26),
            intArrayOf(17, 65),
            intArrayOf(17, 66),
            intArrayOf(7, 38),
            intArrayOf(8, 17),
            intArrayOf(7, 60),
            intArrayOf(0, 16),
            intArrayOf(7, 59),
            intArrayOf(18, 8),
            intArrayOf(16, 63),
            intArrayOf(7, 0),
            intArrayOf(11, 46),
            intArrayOf(0, 7),
            intArrayOf(6, 4),
            intArrayOf(2, 63),
            intArrayOf(8, 56),
            intArrayOf(18, 18),
            intArrayOf(12, 70),
            intArrayOf(2, 15),
            intArrayOf(14, 65),
            intArrayOf(13, 52),
            intArrayOf(11, 0),
            intArrayOf(10, 48),
            intArrayOf(7, 8),
            intArrayOf(11, 44),
            intArrayOf(0, 35),
            intArrayOf(4, 64),
            intArrayOf(6, 36),
            intArrayOf(16, 17),
            intArrayOf(7, 34),
            intArrayOf(1, 33),
            intArrayOf(11, 60),
            intArrayOf(17, 11),
            intArrayOf(4, 58),
            intArrayOf(4, 9),
            intArrayOf(18, 7),
            intArrayOf(15, 40),
            intArrayOf(11, 24),
            intArrayOf(17, 3),
            intArrayOf(7, 9),
            intArrayOf(1, 38),
            intArrayOf(1, 14),
            intArrayOf(15, 21),
            intArrayOf(14, 68),
            intArrayOf(14, 69),
            intArrayOf(16, 40),
            intArrayOf(5, 60),
            intArrayOf(18, 46),
            intArrayOf(15, 51),
            intArrayOf(7, 65),
            intArrayOf(1, 34),
            intArrayOf(15, 55),
            intArrayOf(19, 63),
            intArrayOf(5, 35),
            intArrayOf(20, 9),
            intArrayOf(13, 1),
            intArrayOf(20, 69),
            intArrayOf(19, 67),
            intArrayOf(17, 44),
            intArrayOf(12, 44),
            intArrayOf(10, 49),
            intArrayOf(12, 43),
            intArrayOf(14, 21),
            intArrayOf(18, 11),
            intArrayOf(11, 9),
            intArrayOf(4, 56),
            intArrayOf(6, 70),
            intArrayOf(8, 54),
            intArrayOf(1, 55),
            intArrayOf(17, 47),
            intArrayOf(18, 38),
            intArrayOf(3, 31),
            intArrayOf(16, 37),
            intArrayOf(13, 7),
            intArrayOf(15, 6),
            intArrayOf(18, 33),
            intArrayOf(4, 60),
            intArrayOf(17, 40),
            intArrayOf(7, 3),
            intArrayOf(3, 32),
            intArrayOf(13, 41),
            intArrayOf(5, 62),
            intArrayOf(17, 4),
            intArrayOf(20, 5),
            intArrayOf(15, 32),
            intArrayOf(19, 31),
            intArrayOf(8, 69),
            intArrayOf(19, 58),
            intArrayOf(3, 35),
            intArrayOf(6, 64),
            intArrayOf(0, 37),
            intArrayOf(15, 56),
            intArrayOf(6, 46),
            intArrayOf(4, 42),
            intArrayOf(4, 51),
            intArrayOf(2, 7),
            intArrayOf(7, 13),
            intArrayOf(20, 47),
            intArrayOf(10, 29),
            intArrayOf(12, 18),
            intArrayOf(20, 52),
            intArrayOf(5, 5),
            intArrayOf(12, 34),
            intArrayOf(1, 57),
            intArrayOf(7, 32),
            intArrayOf(3, 58),
            intArrayOf(14, 29),
            intArrayOf(2, 32),
            intArrayOf(2, 46),
            intArrayOf(14, 5),
            intArrayOf(3, 9),
            intArrayOf(19, 68),
            intArrayOf(18, 16),
            intArrayOf(19, 2),
            intArrayOf(6, 23),
            intArrayOf(20, 3),
            intArrayOf(10, 69),
            intArrayOf(9, 0),
            intArrayOf(0, 13),
            intArrayOf(20, 38),
            intArrayOf(6, 14),
            intArrayOf(0, 21),
            intArrayOf(6, 50),
            intArrayOf(2, 5),
            intArrayOf(1, 20),
            intArrayOf(5, 20),
            intArrayOf(1, 5),
            intArrayOf(10, 0),
            intArrayOf(7, 6),
            intArrayOf(15, 13),
            intArrayOf(8, 21),
            intArrayOf(7, 14),
            intArrayOf(9, 9),
            intArrayOf(19, 8),
            intArrayOf(13, 25),
            intArrayOf(5, 30),
            intArrayOf(1, 16),
            intArrayOf(18, 19),
            intArrayOf(16, 44),
            intArrayOf(4, 5),
            intArrayOf(15, 37),
            intArrayOf(20, 14),
            intArrayOf(20, 8),
            intArrayOf(5, 23),
            intArrayOf(13, 44),
            intArrayOf(17, 56),
            intArrayOf(13, 62),
            intArrayOf(2, 18),
            intArrayOf(1, 58),
            intArrayOf(17, 2),
            intArrayOf(20, 40),
            intArrayOf(8, 9),
            intArrayOf(8, 52),
            intArrayOf(6, 24),
            intArrayOf(19, 65),
            intArrayOf(7, 48),
            intArrayOf(20, 51),
            intArrayOf(2, 21),
            intArrayOf(7, 39),
            intArrayOf(11, 27),
            intArrayOf(7, 22),
            intArrayOf(12, 6),
            intArrayOf(19, 12),
            intArrayOf(12, 66),
            intArrayOf(0, 55),
            intArrayOf(20, 62),
            intArrayOf(11, 20),
            intArrayOf(2, 35),
            intArrayOf(2, 0),
            intArrayOf(6, 7),
            intArrayOf(5, 41),
            intArrayOf(9, 37),
            intArrayOf(8, 44),
            intArrayOf(16, 15),
            intArrayOf(9, 48),
            intArrayOf(18, 54),
            intArrayOf(19, 52),
            intArrayOf(19, 24),
            intArrayOf(19, 46),
            intArrayOf(5, 0),
            intArrayOf(19, 50),
            intArrayOf(2, 37),
            intArrayOf(18, 31),
            intArrayOf(6, 20),
            intArrayOf(4, 59),
            intArrayOf(5, 39),
            intArrayOf(9, 38),
            intArrayOf(19, 51),
            intArrayOf(3, 67),
            intArrayOf(11, 33),
            intArrayOf(7, 57),
            intArrayOf(13, 47),
            intArrayOf(20, 64),
            intArrayOf(8, 24),
            intArrayOf(13, 69),
            intArrayOf(4, 11),
            intArrayOf(4, 46),
            intArrayOf(13, 32),
            intArrayOf(18, 3),
            intArrayOf(20, 54),
            intArrayOf(18, 17),
            intArrayOf(7, 5),
            intArrayOf(15, 12),
            intArrayOf(12, 7),
            intArrayOf(6, 11),
            intArrayOf(5, 4),
            intArrayOf(17, 26),
            intArrayOf(7, 12),
            intArrayOf(12, 68),
            intArrayOf(8, 45),
            intArrayOf(8, 2),
            intArrayOf(15, 34),
            intArrayOf(12, 20),
            intArrayOf(1, 26),
            intArrayOf(6, 54),
            intArrayOf(19, 16),
            intArrayOf(0, 17),
            intArrayOf(9, 13),
            intArrayOf(4, 65),
            intArrayOf(12, 58),
            intArrayOf(11, 52),
            intArrayOf(8, 32),
            intArrayOf(18, 32),
            intArrayOf(11, 50),
            intArrayOf(9, 50),
            intArrayOf(17, 13),
            intArrayOf(11, 17),
            intArrayOf(16, 53),
            intArrayOf(18, 26),
            intArrayOf(2, 42),
            intArrayOf(14, 58),
            intArrayOf(0, 23),
            intArrayOf(19, 44),
            intArrayOf(9, 39),
            intArrayOf(15, 47),
            intArrayOf(11, 70),
            intArrayOf(10, 35),
            intArrayOf(8, 41),
            intArrayOf(15, 39),
            intArrayOf(20, 50),
            intArrayOf(2, 50),
            intArrayOf(17, 39),
            intArrayOf(1, 28),
            intArrayOf(7, 63),
            intArrayOf(16, 61),
            intArrayOf(15, 58),
            intArrayOf(19, 17),
            intArrayOf(11, 40),
            intArrayOf(20, 46),
            intArrayOf(12, 41),
            intArrayOf(6, 32),
            intArrayOf(2, 67),
            intArrayOf(4, 52),
            intArrayOf(14, 24),
            intArrayOf(0, 43),
            intArrayOf(17, 34),
            intArrayOf(6, 56),
            intArrayOf(2, 53),
            intArrayOf(1, 69),
            intArrayOf(0, 11),
            intArrayOf(16, 48),
            intArrayOf(1, 47),
            intArrayOf(14, 12),
            intArrayOf(7, 23),
            intArrayOf(8, 37),
            intArrayOf(17, 18),
            intArrayOf(7, 27),
            intArrayOf(7, 2),
            intArrayOf(10, 63),
            intArrayOf(13, 6),
            intArrayOf(3, 23),
            intArrayOf(12, 8),
            intArrayOf(1, 52),
            intArrayOf(11, 30),
            intArrayOf(9, 57),
            intArrayOf(16, 57),
            intArrayOf(9, 58),
            intArrayOf(4, 38),
            intArrayOf(18, 36),
            intArrayOf(10, 17),
            intArrayOf(20, 24),
            intArrayOf(13, 64),
            intArrayOf(18, 37),
            intArrayOf(4, 21),
            intArrayOf(17, 33),
            intArrayOf(2, 33),
            intArrayOf(15, 10),
            intArrayOf(8, 40),
            intArrayOf(14, 52),
            intArrayOf(19, 1),
            intArrayOf(2, 45),
            intArrayOf(11, 55),
            intArrayOf(3, 40),
            intArrayOf(8, 31),
            intArrayOf(20, 57),
            intArrayOf(6, 33),
            intArrayOf(6, 22),
            intArrayOf(6, 28),
            intArrayOf(2, 11),
            intArrayOf(4, 15),
            intArrayOf(4, 31),
            intArrayOf(16, 26),
            intArrayOf(9, 27),
            intArrayOf(10, 61),
            intArrayOf(5, 52),
            intArrayOf(3, 68),
            intArrayOf(0, 19),
            intArrayOf(13, 40),
            intArrayOf(0, 52),
            intArrayOf(18, 22),
            intArrayOf(1, 24),
            intArrayOf(13, 29),
            intArrayOf(12, 33),
            intArrayOf(16, 58),
            intArrayOf(19, 66),
            intArrayOf(6, 62),
            intArrayOf(18, 40),
            intArrayOf(17, 58),
            intArrayOf(2, 34),
            intArrayOf(15, 63),
            intArrayOf(8, 23),
            intArrayOf(14, 50),
            intArrayOf(20, 16),
            intArrayOf(6, 9),
            intArrayOf(8, 1),
            intArrayOf(3, 0),
            intArrayOf(20, 10),
            intArrayOf(15, 23),
            intArrayOf(1, 0),
            intArrayOf(13, 4),
            intArrayOf(8, 25),
            intArrayOf(10, 13),
            intArrayOf(12, 9),
            intArrayOf(18, 39),
            intArrayOf(3, 24),
            intArrayOf(20, 63),
            intArrayOf(16, 39),
            intArrayOf(7, 36),
            intArrayOf(15, 65),
            intArrayOf(13, 10),
            intArrayOf(19, 20),
            intArrayOf(3, 54),
            intArrayOf(12, 35),
            intArrayOf(17, 49),
            intArrayOf(17, 31),
            intArrayOf(14, 48),
            intArrayOf(18, 65),
            intArrayOf(2, 44),
            intArrayOf(9, 51),
            intArrayOf(17, 64),
            intArrayOf(16, 36),
            intArrayOf(7, 10),
            intArrayOf(5, 9),
            intArrayOf(12, 13),
            intArrayOf(6, 59),
            intArrayOf(13, 21),
            intArrayOf(8, 14),
            intArrayOf(10, 67),
            intArrayOf(20, 56),
            intArrayOf(6, 53),
            intArrayOf(18, 25),
            intArrayOf(14, 39),
            intArrayOf(8, 70),
            intArrayOf(10, 27),
            intArrayOf(0, 48),
            intArrayOf(0, 36),
            intArrayOf(12, 56),
            intArrayOf(3, 28),
            intArrayOf(15, 14),
        )
        val answer = NumberofIslandsII().numIslands2(21, 71, positions)
        val answer2 = NumberofIslandsII().numIslands2_bruteforce(21, 71, positions)
        assertEquals(answer2, answer)
    }

    @Test
    fun `stress test`() {
        var testCase = 1
        (100..200).forEach { size ->
            val m = Random(size).nextInt(size) + 1
            val n = Random(size).nextInt(size) + 1
            (0..20).map {
                val positions = (0..(Random(size).nextInt(m * n))).map {
                    val x = Random(size).nextInt(m)
                    val y = Random(size).nextInt(n)
                    intArrayOf(x, y)
                }
                println("running test case #${testCase++}")
                val bruteforce = NumberofIslandsII().numIslands2_bruteforce(m, n, positions.toTypedArray())
                val fast = NumberofIslandsII().numIslands2(m, n, positions.toTypedArray())
                if (bruteforce != fast) {
                    println("$m $n")
                    positions.forEach { (x, y) ->
                        println("$x $y")
                    }
                    return
                }
            }
        }
    }
}